---
features:
  - |
    Add ability to set the environment variable ``RABBITMQ_USE_LONGNAMES``
    via the ``rabbitmq-env.conf`` to be able to use the FQDN of a node.
    By default this will be set to ``false``, the default value also set
    by RabbitMQ.
