node_exporter_web_listen_address: "{{ ansible_host }}:9100"

prometheus_targets:
  node_exporter: 
    - targets: "{{ groups['hosts']|product([':9100'])|map('flatten')|map('join')|list }}"
  mysqld_exporter: 
    - targets: "{{ groups['hosts']|product([':9104'])|map('flatten')|map('join')|list }}"
  
prometheus_scrape_configs:
  - job_name: "node_exporter"    # Custom scrape job, here using `static_config`
    metrics_path: "/metrics"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node_exporter.yml"
  - job_name: "mysqld_exporter"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/mysqld_exporter.yml"