node_exporter_web_listen_address: "{{ ansible_host }}:9100"

prometheus_targets:
  node_exporter: 
    - targets: >- 
        {% for ip in groups['hosts']  %}
        - {{ip}}+":9104"
        {% endfor %}
  mysqld_exporter: 
    - targets: >- 
        {% for ip in groups['galera_container']  %}
        - {{ip}}+":9104"
        {% endfor %}

prometheus_scrape_configs:
  - job_name: "node_exporter"    # Custom scrape job, here using `static_config`
    metrics_path: "/metrics"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node_exporter.yml"
  - job_name: "mysqld_exporter"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/mysqld_exporter.yml"