
- name: Refresh local facts
  gather_facts: false
  hosts: prometheus_containers
  tasks:
    - name: Refresh local facts
      setup:


- name: prometheus
  hosts: prometheus_containers
  vars_files:
    - vars/variables.yml
  vars:
    prometheus_web_listen_address: "{{ansible_host}}:9090"
  roles:
    - role: prometheus.prometheus.prometheus
