
- name: Refresh local facts
  gather_facts: false
  hosts: prometheus_all
  tasks:
    - name: Refresh local facts
      setup:


- name: prometheus
  hosts: prometheus_all
  vars_files:
    - vars/variables.yml
  roles:
    - role: prometheus.prometheus.prometheus
