---
component_skel:
  apm-server:
    belongs_to:
      - elk_all
      - apm_all
  elastic:
    belongs_to:
      - elk_all
  logstash:
    belongs_to:
      - elk_all
  kibana:
    belongs_to:
      - elk_all

container_skel:
  apm-server_container:
    belongs_to:
      - apm-server_containers
    contains:
      - apm-server
  elastic-logstash_container:
    belongs_to:
      - elastic-logstash_containers
    contains:
      - elastic
      - logstash
  elastic_container:
    belongs_to:
      - elastic_containers
    contains:
      - elastic
  logstash_container:
    belongs_to:
      - logstash_containers
    contains:
      - logstash
  kibana_container:
    belongs_to:
      - kibana_containers
    contains:
      - kibana

physical_skel:
  apm-server_containers:
    belongs_to:
      - all_containers
  apm-server_hosts:
    belongs_to:
      - hosts
  elastic-logstash_containers:
    belongs_to:
      - all_containers
  elastic-logstash_hosts:
    belongs_to:
      - hosts
  elastic_containers:
    belongs_to:
      - all_containers
  elastic_hosts:
    belongs_to:
      - hosts
  logstash_containers:
    belongs_to:
      - all_containers
  logstash_hosts:
    belongs_to:
      - hosts
  kibana_containers:
    belongs_to:
      - all_containers
  kibana_hosts:
    belongs_to:
      - hosts
