beat_version: "7.17.9"
default_ilm_rollover_max_size: "30G"
default_ilm_rollover_max_age: "15d"
default_ilm_delete_min_age: "30d"
default_ilm_policy:
  policy:
    phases:
      hot:
        actions:
          rollover:
            max_size: "{{ default_ilm_rollover_max_size }}"
            max_age: "{{ default_ilm_rollover_max_age }}"
      delete:
        min_age: "{{ default_ilm_delete_min_age }}"
        actions:
          delete: {}
default_ilm_policy_filename: "default-ilm-policy.json"
default_ilm_policy_file_location: "/tmp"

elastic_beat_no_proxy: "{{ hostvars[groups['elastic'][0]]['ansible_host'] }}"

# beats_setup_username: ""
# beats_setup_password: ""
