---

################################## ALL HOSTS ##################################
all:
  hosts:
    # Local host
    localhost:
      ansible_connection: local

################################## REQUIRED ###################################
    logging01:
      ansible_host: 172.16.27.100
      ansible_user: root

  vars: {}


################################### GROUPS ####################################

# The hosts group is used to target physical host machines. Enter all physical
# host machines here.
hosts:
  hosts:
    logging01:

# This is the location where grafana(s) will live
grafana_all:
  hosts:
    logging01:
