---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Initialise arcsight local facts
  ini_file:
    dest: "/etc/ansible/facts.d/logstash.fact"
    section: arcsight
    option: "initialise"
    value: true

- name: refresh local facts
  setup:
    filter: ansible_local
    gather_subset: "!all"
  tags:
    - nova-config

- name: Setup arcsight smart connector
  shell: >-
    /usr/local/bin/logstash --modules arcsight {{ (ansible_local['arcsight'][item.host] is defined) | ternary('', '--setup') }}
      -M "arcsight.var.input.smartconnector.bootstrap_servers={{ item.host }}:{{ item.port }}"
      -M "arcsight.var.elasticsearch.hosts=localhost:{{ elastic_port }}"
      -M "arcsight.var.kibana.host={{ hostvars[groups['kibana'][0]]['ansible_host'] }}:{{ kibana_port }}"
  with_items: "{{ logstash_arcsight_smart_connectors }}"
  run_once: true
  register: smart_connector
  until: smart_connector is success
  retries: 5
  delay: 5

- name: Setup arcsight event broker
  shell: >-
    /usr/local/bin/logstash --modules arcsight {{ (ansible_local['arcsight'][item.host] is defined) | ternary('', '--setup') }}
      -M "arcsight.var.input.eventbroker.bootstrap_servers={{ item.host }}:{{ item.port }}"
      -M "arcsight.var.elasticsearch.hosts=localhost:{{ elastic_port }}"
      -M "arcsight.var.kibana.host={{ hostvars[groups['kibana'][0]]['ansible_host'] }}:{{ kibana_port }}"
  with_items: "{{ logstash_arcsight_event_brokers }}"
  run_once: true
  register: event_broker
  until: event_broker is success
  retries: 5
  delay: 5

- name: Set arcsight local facts
  ini_file:
    dest: "/etc/ansible/facts.d/logstash.fact"
    section: arcsight
    option: "{{ item.host }}"
    value: "{{ item.port }}"
  with_items: "{{ logstash_arcsight_smart_connectors | union(logstash_arcsight_event_brokers) }}"
